---
AWSTemplateFormatVersion: '2010-09-09'
Description: Private hosted zone with associated VPCs.

# Parameters
# NOTE: The CIDRs of the associated VPCs must not overlap.
Parameters:
  Name:
    Type: String
    Description: The domain name of the hosted zone. E.g., mycompany.net
  Comment:
    Type: String
    Description: Optional comments. E.g., Internal Only
  VPC1Id:
    Type: String
    Description: The ID of the frist VPC.
  VPC1Region:
    Type: String
    Description: The region of the first VPC.
  VPC2Id:
    Type: String
    Description: The ID of the second VPC.
  VPC2Region:
    Type: String
    Description: The region of the second VPC.
  VPC3Id:
    Type: String
    Description: The ID of the third VPC.
  VPC3Region:
    Type: String
    Description: The region of the third VPC.
  VPC4Id:
    Type: String
    Description: The ID of the fourth VPC.
  VPC4Region:
    Type: String
    Description: The region of the fourth VPC.
  VPC5Id:
    Type: String
    Description: The ID of the fifth VPC.
  VPC5Region:
    Type: String
    Description: The region of the fifth VPC.

# Conditions
Conditions:
  HasSecondVPC: !And [
    !Not [!Equals ['', !Ref VPC2Id]],
    !Not [!Equals ['', !Ref VPC2Region]]]
  HasThirdVPC: !And [
    !Not [!Equals ['', !Ref VPC3Id]],
    !Not [!Equals ['', !Ref VPC3Region]]]
  HasFourthVPC: !And [
    !Not [!Equals ['', !Ref VPC4Id]],
    !Not [!Equals ['', !Ref VPC4Region]]]
  HasFifthVPC: !And [
    !Not [!Equals ['', !Ref VPC5Id]],
    !Not [!Equals ['', !Ref VPC5Region]]]

# Metadata
Metadata:
  AWS::CloudFormation::Interface:

    # Parameter Groups
    ParameterGroups:
      - Label:
          default: Hosted Zone
        Parameters:
        - Name
        - Comment
      - Label:
          default: First VPC
        Parameters:
        - VPC1Id
        - VPC1Region
      - Label:
          default: Second VPC (optional)
        Parameters:
        - VPC2Id
        - VPC2Region
      - Label:
          default: Third VPC (optional)
        Parameters:
        - VPC3Id
        - VPC3Region
      - Label:
          default: Fourth VPC (optional)
        Parameters:
        - VPC4Id
        - VPC4Region
      - Label:
          default: Fith VPC (optional)
        Parameters:
        - VPC5Id
        - VPC5Region

    # Parameter Labels
    ParameterLabels:
      Name:
        default: Domain Name
      VPC1Id:
        default: VPC Id
      VPC1Region:
        default: Region
      VPC2Id:
        default: VPC Id
      VPC2Region:
        default: Region
      VPC3Id:
        default: VPC Id
      VPC3Region:
        default: Region
      VPC4Id:
        default: VPC Id
      VPC4Region:
        default: Region
      VPC5Id:
        default: VPC Id
      VPC5Region:
        default: Region

# Resrouces
Resources:
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref Name
      HostedZoneConfig:
        Comment: !Ref Comment
      VPCs:
      - VPCId: !Ref VPC1Id
        VPCRegion: !Ref VPC1Region
      - Fn::If:
        - HasSecondVPC
        - VPCId:
            Ref: VPC2Id
          VPCRegion:
            Ref: VPC2Region
        - Ref: AWS::NoValue
      - Fn::If:
        - HasThirdVPC
        - VPCId:
            Ref: VPC3Id
          VPCRegion:
            Ref: VPC3Region
        - Ref: AWS::NoValue
      - Fn::If:
        - HasFourthVPC
        - VPCId:
            Ref: VPC4Id
          VPCRegion:
            Ref: VPC4Region
        - Ref: AWS::NoValue
      - Fn::If:
        - HasFifthVPC
        - VPCId:
            Ref: VPC5Id
          VPCRegion:
            Ref: VPC5Region
        - Ref: AWS::NoValue

# Outputs
Outputs:
  HostedZoneId:
    Description: The hosted zone
    Value:
      Ref: HostedZone
    Export:
      Name:
        Fn::Sub:
          ${AWS::StackName}:hosted-zone-id
